### ISSUE TITLE
Join the sopel-irc organization?

### ISSUE THREAD

**Issue by dgw** [savoiringfaire/puppet-sopel#2]
Hi!

Apologies for hijacking your issue tracker like this, @savoiringfaire, but I couldn't figure out any other way to get in touch with you. Your profiles here and on Puppet Forge are sparse indeed!

I'm the overall maintainer of all @sopel-irc projects, and I'd love to see your puppet-sopel module join the organization alongside its cousins [ansible-sopel](https://github.com/sopel-irc/ansible-sopel) and [docker-sopel](https://github.com/sopel-irc/docker-sopel).

You would remain primary maintainer of puppet-sopel, as you are now. Joining the organization simply provides a succession plan, in case you later decide you no longer want to maintain this Puppet module, or you become unable to continue updating it.

We would also (hopefully) set up automated publishing via Travis CI to an "official" Sopel namespace or profile on Puppet Forge, again providing a succession plan for the future (so it's not tied to your `savoirfaire` namespace).

If you're willing to at least talk about this, drop a reply here and/or ping me (`dgw`) on freenode IRC. I look forward to hearing from you!

**Comment by savoiringfaire** [comment]
Hi @dgw!

No problem about the issue tracker - my fault for not having an email visible :) I'd definitely be up for talking about it - seems like a great idea to me.

I'll close this issue for now, and jump on IRC when I get a moment - what timezone are you in and when would be the best time to try and catch you?

**Comment by dgw** [comment]
Hey, guess I missed you on IRC today. I'm in the `America/Chicago` timezone, but I'm on IRC only when I'm not running around IRL. Should be around later tonight, if you come back online before ~1-2 CDT, or most of the day tomorrow. Sundays are pretty free for me, unless some plan comes up (and with family around, sometimes that happens). We'll find a time to connect, I know it!
